apiVersion: apps/v1
kind: Deployment
metadata:
  name: baseline-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx-container
        image: docker.io/nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 100m
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        - name: web-logs
          mountPath: /var/log/nginx        # <-- Mount disk to Nginx log path
      volumes:
      - name: html-volume
        configMap:
          name: web-landing-page
      - name: web-logs
        persistentVolumeClaim:
          claimName: web-log-pvc           # <-- Connect to your PVC
